### ISSUE TITLE
Wrong class referenced on oauthAuthorize.jsp

### ISSUE THREAD

**Issue by hir0pr0tagonist** [Talend/tesb-rt-se#53]
The jsp references "org.apache.cxf.rs.security.oauth2.common.Permission", but what is required is "org.apache.cxf.rs.security.oauth2.common.OAuthPermission". A simple replace makes the example under examples\cxf\jaxrs-oauth2 run correctly.

**Comment by xldai** [comment]
Could you please open a PR for it? Thanks

**Comment by hir0pr0tagonist** [comment]
Done.

**Comment by andreasmattes** [comment]
Closed as inactive.
